### ISSUE TITLE
Double tilde in chain output is strikethrough tag in Discord

### ISSUE THREAD

**Issue by Jambe** [secondfry/shortcircuit#1]
The "FC, please help!" route output uses a double tilde followed by a greater-than sign [ ~~> ] to indicate a wormhole jump.

If there's more than one wormhole in the route then you get two pairs of tildes with other (important) characters in between, which Discord parses by removing the surrounding tildes and applying a strikethrough to the characters in between.

Perhaps a different string can be used to indicate a wormhole jump?

You're doing great work on the program, btw; thanks!

**Comment by secondfry** [comment]
Good point, I will tackle it and release fixed version something around next Monday.
