### ISSUE TITLE
Displaying Options

### ISSUE THREAD

**Issue by Bobbarry51** [secondfry/shortcircuit#11]
Short Circuit is an excellent program. I hate to call this an issue, more just looking for some advice. I am running Windows 10 64-bit with display resolution of 3840 X 2160 Landscape with text set to 250%.  I have tried many different resolutions and text sizes. The far right “Options” section has words cut off and the text is too large for the buttons. I have honestly tried various text sizes with different resolutions and the result is the same. I have also run the program in Windows 7 mode. I would like to increase the width of the “Options” column in hopes that solves the problem. I did try to work with Qt but that is beyond my abilities. I also note the Tripwire sign in window is compressed and difficult to read. Any thoughts would be appreciated. I do know this is an older program and I am not asking to take up anyone’s time, just any ideas on how to display the “Options” better. I will attempt to include a screen shot with this message.
Thank you for your time.

![SC lettering](https://user-images.githubusercontent.com/98258442/167958167-8de04061-5ef6-4729-807a-17690dcc349e.jpg)
R

**Comment by secondfry** [comment]
I was kinda able to make Short Circuit work on Apple Silicon (my only computer at the moment) so I will try to investigate what could be done so it would properly react to text scale.

**Comment by Bobbarry51** [comment]
This has been resolved. I am not totally familiar with github. I will attempt to close with this comment.
