### ISSUE TITLE
Max height 865 pixels (not great for smaller resolutions)

### ISSUE THREAD

**Issue by Jambe** [secondfry/shortcircuit#2]
If one maximizes SC on a 1366x768 screen, it will collapse below its default height, but then it looks like this:

https://i.imgur.com/KisoMog.png

Note that the avoidance list is reduced to a tiny sliver (it's not really usable).

When non-maximized, the window seems to have a max height of 865 pixels, which means it can't fit on a screen with a smaller height. Here's an example:

https://i.imgur.com/bbPUk5s.png

The Set in-game destination, Delete Selected, Clear List and Reset Chain buttons disappear below the taskbar along with the selected destination and route info boxes. Also, even when maximized (and thus crunched down) sometimes alt-tabbing back and updating the chain or finding a new path will cause the window to expand back up to 865 pixels.

It'd be nice if SC was a touch more usable for plebs like me who sometimes play on older laptops with smallish resolutions.

Dunno how to fix this; perhaps if the SC banner were shrunk to the left, allowing the Options pane to reach all the way to the top of the window, there'd be enough room for everything.

**Comment by secondfry** [comment]
Thank you for this report, I will tackle the issue.

**Comment by Jambe** [comment]
Thanks for your work on SC!

I took a look at fixing it myself, but my unfamiliarity with Qt prevented that.

**Comment by secondfry** [comment]
Closed via:
40732b064ff11db66d0500328fb0cdea9ef2e639
3409aafde7388ee4f897e469514ba5b0d38a8e17
5cca82328631d1c5e4f080f377dc27f34d1ca0ef
8499e2c143ba9f05de0d5d2d0e39bd990173ae23
6714663b214fcc0204611e645ac7315d5a94de1d
5e67424aad1767f26e5d8dbbe8e6c2d501fbef67
