### ISSUE TITLE
Can not run ShortCircuit on Win7

### ISSUE THREAD

**Issue by rossos** [secondfry/shortcircuit#4]
Downloaded latest 0.5.0 executable and replaced the old (0.4.x) executable in the same folder. Trying to run the new file gives me two errors in a row, and the application does not launch:

`System error:
The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer.`

`Fatal error detected:
Error loading Python DLL
'C:\Users\...\AppData\Local\Temp\..\python39.dll'
LoadLibrary: The specified module could not be found.`

I am trying to run this on a Windows 7 machine, which I assume is the source of this error.

**Comment by secondfry** [comment]
Damn, I hoped this won't be the case. I'll tackle this ASAP. Thank you for report!

**Comment by secondfry** [comment]
About `api-ms-win-core-path-l1-1-0.dll`:
I couldn't find it from official sources – I've checked Windows 10 SDK, vcredist 2015-2019, vcredist 2015.
So I had to download it from 3rd party source, but seemingly it is original dll – https://www.virustotal.com/gui/file/e39ca111d81e6e5d90cf13fa0aee525d8a2740b84d2c5cd378dd69e4f79f8b0f/detection.
I've added it to build script.

Regarding python39.dll `LoadLibrary` failure – it seems this one should be related to previous one even tho apparently Python 3.9 dropped support for Windows 7.

@rossos, can you please test https://github.com/secondfry/shortcircuit/releases/tag/v0.5.1-pre.1?
If it would still fail to load, I will just make Python 3.8 release for Windows 7.

**Comment by secondfry** [comment]
Looking for anyone to test https://github.com/secondfry/shortcircuit/releases/tag/v0.5.1-pre.1 on Windows 7.

**Comment by secondfry** [comment]
Thank you, closing the issue.
