### ISSUE TITLE
0.5.1 release unhappy with Win7

### ISSUE THREAD

**Issue by rossos** [secondfry/shortcircuit#9]
Possibly related to #4 as it also references Python3.9 on Win7...

Downloading the latest 0.5.1 release and attempting to run, the executable crashes with a "shortcircuit.exe has stopped working" Windows prompt and the following crash information attached:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	shortcircuit.exe
  Application Version:	0.0.0.0
  Application Timestamp:	61062592
  Fault Module Name:	python39.dll
  Fault Module Version:	3.9.7150.1013
  Fault Module Timestamp:	612d3e3d
  Exception Code:	c0000005
  Exception Offset:	000000000006fc53
  OS Version:	6.1.7601.2.1.0.256.48
```

Notably, this does not occur with the 0.5.1-rc.1 (pre-release) executable, which instead runs as expected.

**Comment by secondfry** [comment]
Thank you for this report!
I've switched to Python 3.8 both locally and in GitHub CI.

@rossos can you please test https://github.com/secondfry/shortcircuit/releases/tag/v0.5.2-rc.1? As I've mentioned there it would be absolutely wonderful to hear if CI build packed by UPX works for you.

**Comment by rossos** [comment]
The first option 'shortcircuit-v0.5.2-rc.1-windows-x64-CI-upx.zip' launches and appears to work fine, no observed issues.

**Comment by secondfry** [comment]
Amazing news!

For now I'll close this issue and pin it, because I don't want to release a version with changes just being supporting EOL OS.
